version: '3'

services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    ports:
      - 8581:8581
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - UMASK_SET=022 #optional
    volumes:
      - /share/Container/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
