version: '3'

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /share/SheridanFlix/Config/Sonarr:/config
      - /share/SheridanFlix/Downloads:/download
      - /share/SheridanFlix/TV/Adults:/tv
      - /share/SheridanFlix/TV/Kids:/tv_kids
    ports:
      - 8989:8989
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /share/SheridanFlix/Config/Nzbget:/config
      - /share/SheridanFlix/Downloads:/download
    ports:
      - 6789:6789
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /share/SheridanFlix/Config/Radarr:/config
      - /share/SheridanFlix/Movies/Adults:/movies
      - /share/SheridanFlix/Movies/Adults:/Movies
      - /share/SheridanFlix/Movies/Kids:/movies_kids
      - /share/SheridanFlix/Downloads/movies:/downloads
      - /share/SheridanFlix/Downloads:/download
    ports:
      - 7878:7878
    restart: unless-stopped
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=merica/Los_Angeles
    volumes:
      - /share/SheridanFlix/Config/nzbhydra:/config
      - /share/SheridanFlix/Downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /share/SheridanFlix/Config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8181:8181
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /share/SheridanFlix/Config/overseerr:/app/config
    restart: unless-stopped
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PMM_CONFIG=/config/config.yml #optional
      - PMM_TIME=02:00,03:00 #optional
      - PMM_RUN=true #optional
      - PMM_TEST=False #optional
      - PMM_NO_MISSING=False #optional
    volumes:
      -  /share/SheridanFlix/Config/plexmetamanager:/config
    restart: unless-stopped
  plex-cleaner:
    image: nitrikx/plex-cleaner
    container_name: plex-cleaner
    environment:
      # Execute the script every 5 minutes
      - EXECUTION_CRON_EXPRESSION=*/5 * * * *
    volumes:
      -  /share/SheridanFlix/Config/plexcleaner/config:/config
      -  /share/SheridanFlix/Config/plexmetamanager/logs:/logs
      # - ./plexdata:/plexdata
      # - ./logs:/logs

