version: '3'

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /share/Public/SheridanFlix/Config/Sonarr:/config
      - /share/Public/SheridanFlix/Downloads/tv:/download
      - /share/Public/SheridanFlix/TV/Brian:/tv
      - /share/Public/SheridanFlix/TV/Classic:/tv_classic
      - /share/Public/SheridanFlix/TV/Heidi:/tv_heidi
      - /share/Public/SheridanFlix/TV/Kids:/tv_kids
      - /share/Public/SheridanFlix/TV/Cartoons:/tv_cartoons
    ports:
      - 8989:8989
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /share/Public/SheridanFlix/Config/Nzbget:/config
      - /share/Public/SheridanFlix/Downloads:/download
    ports:
      - 6789:6789
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /share/Public/SheridanFlix/Config/Radarr:/config
      - /share/Public/SheridanFlix/Movies/Adult:/movies
      - /share/Public/SheridanFlix/Movies/Adult:/Movies
      - /share/Public/SheridanFlix/Movies/Kids:/movies_kids
      - /share/Public/SheridanFlix/Downloads/movies:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /share/Public/SheridanFlix/Config/nzbhydra:/config
      - /share/Public/Download:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /share/Public/SheridanFlix/Config/Plex:/config
      - /share/Public/SheridanFlix/TV/Brian:/tv_brian
      - /share/Public/SheridanFlix/TV/Classic:/tv_classic
      - /share/Public/SheridanFlix/TV/Heidi:/tv_heidi
      - /share/Public/SheridanFlix/TV/Kids:/tv_kids
      - /share/Public/SheridanFlix/TV/Cartoons:/tv_cartoons
      - /share/Public/SheridanFlix/Movies/Adult:/movies
      - /share/Public/SheridanFlix/Movies/Kids:/movies_kids
    restart: unless-stopped