version: '3'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /share/SheridanFlix/Config/Sonarr:/config
      - /share/SheridanFlix/Downloads:/download
      - /share/SheridanFlix/Downloads:/downloads
      - /share/SheridanFlix/TV/Adults:/tv
      - /share/SheridanFlix/TV/Kids:/tv_kids
    ports:
      - 8989:8989
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=merica/Los_Angeles
    volumes:
      - /share/SheridanFlix/Config/sabnzbd:/config
      - /share/SheridanFlix/Downloads:/downloads #optional
      - /share/SheridanFlix/Downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 7890:8080
    restart: unless-stopped
  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1000
      - TZ=merica/Los_Angeles
    ports:
      - 5055:5055
    volumes:
      - /share/SheridanFlix/Config/overseerr:/app/config
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /share/Container/homarr/configs:/app/data/configs
      - /share/Container/homarr:/data
      - /share/Container/homarr:/app/public/icons
    ports:
      - '7575:7575'
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
    volumes:
      - /share/SheridanFlix/Config/Radarr:/config
      - /share/SheridanFlix/Movies/Adults:/movies
      - /share/SheridanFlix/Movies/Adults:/Movies
      - /share/SheridanFlix/Movies/Kids:/movies_kids
      - /share/SheridanFlix/Downloads:/downloads
      - /share/SheridanFlix/Downloads:/download
    ports:
      - 7878:7878
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /share/SheridanFlix/Config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    ports:
      - 8181:8181
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/los_angeles
      - VERSION=docker
    volumes:
      - /share/SheridanFlix/Config/Plex:/config
      - /share/SheridanFlix/Movies/Adults:/movies
      - /share/SheridanFlix/Movies/Kids:/movies_kids
      - /share/SheridanFlix/TV/Adults:/tv
      - /share/SheridanFlix/TV/Kids:/tv_kids
      - /share/SheridanFlix/Music:/music
    ports:
      - 32400:32400
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /share/SheridanFlix/Config/Lidarr:/config
      - /share/SheridanFlix/Music:/music #optional
      - /share/SheridanFlix/Downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /share/SheridanFlix/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
