version: '3'

services:
   watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK_SET=022 #optional
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      command: --cleanup --interval 300
      restart: unless-stopped